apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginxpod
  name: nginxpod
spec:
  containers:
  - image: suleymanakturk/projerepo:v22
    name: nginxpod
    imagePullPolicy: IfNotPresent
  imagePullSecrets:
  - name: dockerhubprivate
